//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Direct.Config.Client.AuthManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:directproject:config/store/082010", ConfigurationName="AuthManager.IAuthManager")]
    public interface IAuthManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IAuthManager/GetUser", ReplyAction="urn:directproject:config/store/082010/IAuthManager/GetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IAuthManager/GetUserConfigStoreFaultFault", Name="ConfigStoreFault")]
        Health.Direct.Config.Store.Administrator GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IAuthManager/ValidateUser", ReplyAction="urn:directproject:config/store/082010/IAuthManager/ValidateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IAuthManager/ValidateUserConfigStoreFaultFa" +
            "ult", Name="ConfigStoreFault")]
        bool ValidateUser(string username, Health.Direct.Config.Store.PasswordHash passwordHash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAuthManagerChannel : Health.Direct.Config.Client.AuthManager.IAuthManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AuthManagerClient : System.ServiceModel.ClientBase<Health.Direct.Config.Client.AuthManager.IAuthManager>, Health.Direct.Config.Client.AuthManager.IAuthManager {
        
        public AuthManagerClient() {
        }
        
        public AuthManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Health.Direct.Config.Store.Administrator GetUser(string username) {
            return base.Channel.GetUser(username);
        }
        
        public bool ValidateUser(string username, Health.Direct.Config.Store.PasswordHash passwordHash) {
            return base.Channel.ValidateUser(username, passwordHash);
        }
    }
}
