REM
REM Installation of Direct
REM
IF ()==(%1) GOTO INSTALL_DEFAULT
SET DIRECT_INSTALL_DIR=%~dpnx1
GOTO INSTALL_CONTINUE

:INSTALL_DEFAULT
SET DIRECT_INSTALL_DIR=%CD%\build

:INSTALL_CONTINUE
IF NOT EXIST %DIRECT_INSTALL_DIR%\james-2.3.2 GOTO INSTALL_DOIT

ECHO "Can't install to %DIRECT_INSTALL_DIR% - file or directory exists"
GOTO ERROR_EXIT

:INSTALL_DOIT
echo "Installing Direct in %DIRECT_INSTALL_DIR%"
SET DIRECT_INSTALL_CD=%CD%
ant -f src\scripts\build.xml
GOTO END

:ERROR_EXIT
REM EXIT 1

:END
REM EXIT 0
