//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Direct.AdminUI {
    
    
    public partial class DomainsPage {
        
        /// <summary>
        /// DomainsMultiView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView DomainsMultiView;
        
        /// <summary>
        /// MasterView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View MasterView;
        
        /// <summary>
        /// DomainListControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Health.Direct.AdminUI.Logic.Views.DomainListControl DomainListControl1;
        
        /// <summary>
        /// NewDomainControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Health.Direct.AdminUI.Logic.Views.NewDomainControl NewDomainControl1;
        
        /// <summary>
        /// DetailsView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View DetailsView;
        
        /// <summary>
        /// DomainDetailsControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Health.Direct.AdminUI.Logic.Views.DomainDetailsControl DomainDetailsControl1;
    }
}
