
package org.nhindirect.wsdl.edge.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.nhindirect.schema.edge.ws.EmailType;
import org.nhindirect.schema.edge.ws.ObjectFactory;
import org.nhindirect.schema.edge.ws.SendResponseType;
import org.nhindirect.schema.edge.ws.StatusRefType;
import org.nhindirect.schema.edge.ws.StatusResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "nhindirectWSEdgePort", targetNamespace = "http://nhindirect.org/wsdl/edge/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NhindirectWSEdgePort {


    /**
     * 
     * @param body
     * @return
     *     returns org.nhindirect.schema.edge.ws.SendResponseType
     */
    @WebMethod(operationName = "SendMessage", action = "http://nhindirect.org/schema/edge/ws/SendMessage")
    @WebResult(name = "SendResponse", targetNamespace = "http://nhindirect.org/schema/edge/ws", partName = "body")
    public SendResponseType sendMessage(
        @WebParam(name = "Message", targetNamespace = "http://nhindirect.org/schema/edge/ws", partName = "body")
        EmailType body);

    /**
     * 
     * @param body
     * @return
     *     returns org.nhindirect.schema.edge.ws.StatusResponseType
     */
    @WebMethod(operationName = "RequestStatus", action = "http://nhindirect.org/schema/edge/ws/RequestStatus")
    @WebResult(name = "StatusResponse", targetNamespace = "http://nhindirect.org/schema/edge/ws", partName = "body")
    public StatusResponseType requestStatus(
        @WebParam(name = "Status", targetNamespace = "http://nhindirect.org/schema/edge/ws", partName = "body")
        StatusRefType body);

}
