//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.20 at 07:20:23 PM EDT 
//


package org.nhind.ccddb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MAIN_FACILITY_NAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FACILITY_OID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DISCHARGES_LAST_24_HOURS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LAST_UPDATE_DATETIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ADMISSIONS_LAST_24_HOURS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DEATHS_IN_LAST_24_HOURS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NUMBER_OF_BEDS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SENDING_FACILITY_ID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NUMBER_OF_ROOMS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "mainfacilityname",
    "facilityoid",
    "dischargeslast24HOURS",
    "lastupdatedatetime",
    "admissionslast24HOURS",
    "deathsinlast24HOURS",
    "numberofbeds",
    "sendingfacilityid",
    "numberofrooms"
})
@XmlRootElement(name = "FACILITY")
public class FACILITY {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "MAIN_FACILITY_NAME", required = true)
    protected String mainfacilityname;
    @XmlElement(name = "FACILITY_OID", required = true)
    protected String facilityoid;
    @XmlElementRef(name = "DISCHARGES_LAST_24_HOURS", type = JAXBElement.class)
    protected JAXBElement<Integer> dischargeslast24HOURS;
    @XmlElementRef(name = "LAST_UPDATE_DATETIME", type = JAXBElement.class)
    protected JAXBElement<String> lastupdatedatetime;
    @XmlElementRef(name = "ADMISSIONS_LAST_24_HOURS", type = JAXBElement.class)
    protected JAXBElement<Integer> admissionslast24HOURS;
    @XmlElementRef(name = "DEATHS_IN_LAST_24_HOURS", type = JAXBElement.class)
    protected JAXBElement<Integer> deathsinlast24HOURS;
    @XmlElementRef(name = "NUMBER_OF_BEDS", type = JAXBElement.class)
    protected JAXBElement<Integer> numberofbeds;
    @XmlElementRef(name = "SENDING_FACILITY_ID", type = JAXBElement.class)
    protected JAXBElement<String> sendingfacilityid;
    @XmlElementRef(name = "NUMBER_OF_ROOMS", type = JAXBElement.class)
    protected JAXBElement<Integer> numberofrooms;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the mainfacilityname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAINFACILITYNAME() {
        return mainfacilityname;
    }

    /**
     * Sets the value of the mainfacilityname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAINFACILITYNAME(String value) {
        this.mainfacilityname = value;
    }

    /**
     * Gets the value of the facilityoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACILITYOID() {
        return facilityoid;
    }

    /**
     * Sets the value of the facilityoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACILITYOID(String value) {
        this.facilityoid = value;
    }

    /**
     * Gets the value of the dischargeslast24HOURS property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getDISCHARGESLAST24HOURS() {
        return dischargeslast24HOURS;
    }

    /**
     * Sets the value of the dischargeslast24HOURS property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setDISCHARGESLAST24HOURS(JAXBElement<Integer> value) {
        this.dischargeslast24HOURS = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the lastupdatedatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLASTUPDATEDATETIME() {
        return lastupdatedatetime;
    }

    /**
     * Sets the value of the lastupdatedatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLASTUPDATEDATETIME(JAXBElement<String> value) {
        this.lastupdatedatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the admissionslast24HOURS property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getADMISSIONSLAST24HOURS() {
        return admissionslast24HOURS;
    }

    /**
     * Sets the value of the admissionslast24HOURS property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setADMISSIONSLAST24HOURS(JAXBElement<Integer> value) {
        this.admissionslast24HOURS = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the deathsinlast24HOURS property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getDEATHSINLAST24HOURS() {
        return deathsinlast24HOURS;
    }

    /**
     * Sets the value of the deathsinlast24HOURS property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setDEATHSINLAST24HOURS(JAXBElement<Integer> value) {
        this.deathsinlast24HOURS = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the numberofbeds property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getNUMBEROFBEDS() {
        return numberofbeds;
    }

    /**
     * Sets the value of the numberofbeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setNUMBEROFBEDS(JAXBElement<Integer> value) {
        this.numberofbeds = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the sendingfacilityid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSENDINGFACILITYID() {
        return sendingfacilityid;
    }

    /**
     * Sets the value of the sendingfacilityid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSENDINGFACILITYID(JAXBElement<String> value) {
        this.sendingfacilityid = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the numberofrooms property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getNUMBEROFROOMS() {
        return numberofrooms;
    }

    /**
     * Sets the value of the numberofrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setNUMBEROFROOMS(JAXBElement<Integer> value) {
        this.numberofrooms = ((JAXBElement<Integer> ) value);
    }

}
