//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.20 at 07:20:23 PM EDT 
//


package org.nhind.ccddb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FACILITY_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PATIENT_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FIRST_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LAST_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MIDDLE_INITIAL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STREET_ADDRESS_1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STREET_ADDRESS_2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TELEPHONE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BIRTH_DATE_TIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LANGUAGE_CODE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ETHNICITY_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AGE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AGE_UNITS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GENDER_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZIP_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRANSACTION_DATE_TIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="COUNTY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CITY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="COUNTRY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PCP_OID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PCP_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ETHNICITY_CODE_SYSTEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ETHNICITY_CODE_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GENDER_CODE_SYSTEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PATIENT_EUID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "facilityid",
    "patientid",
    "firstname",
    "lastname",
    "middleinitial",
    "streetaddress1",
    "streetaddress2",
    "telephone",
    "birthdatetime",
    "languagecode",
    "ethnicitycode",
    "age",
    "ageunits",
    "gendercode",
    "zipcode",
    "state",
    "transactiondatetime",
    "county",
    "city",
    "country",
    "pcpoid",
    "pcpname",
    "ethnicitycodesystem",
    "ethnicitycodename",
    "gendercodesystem",
    "patienteuid"
})
@XmlRootElement(name = "PATIENT")
public class PATIENT {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "FACILITY_ID", required = true)
    protected String facilityid;
    @XmlElement(name = "PATIENT_ID", required = true)
    protected String patientid;
    @XmlElementRef(name = "FIRST_NAME", type = JAXBElement.class)
    protected JAXBElement<String> firstname;
    @XmlElementRef(name = "LAST_NAME", type = JAXBElement.class)
    protected JAXBElement<String> lastname;
    @XmlElementRef(name = "MIDDLE_INITIAL", type = JAXBElement.class)
    protected JAXBElement<String> middleinitial;
    @XmlElementRef(name = "STREET_ADDRESS_1", type = JAXBElement.class)
    protected JAXBElement<String> streetaddress1;
    @XmlElementRef(name = "STREET_ADDRESS_2", type = JAXBElement.class)
    protected JAXBElement<String> streetaddress2;
    @XmlElementRef(name = "TELEPHONE", type = JAXBElement.class)
    protected JAXBElement<String> telephone;
    @XmlElementRef(name = "BIRTH_DATE_TIME", type = JAXBElement.class)
    protected JAXBElement<String> birthdatetime;
    @XmlElement(name = "LANGUAGE_CODE", required = true)
    protected String languagecode;
    @XmlElementRef(name = "ETHNICITY_CODE", type = JAXBElement.class)
    protected JAXBElement<String> ethnicitycode;
    @XmlElementRef(name = "AGE", type = JAXBElement.class)
    protected JAXBElement<String> age;
    @XmlElementRef(name = "AGE_UNITS", type = JAXBElement.class)
    protected JAXBElement<String> ageunits;
    @XmlElementRef(name = "GENDER_CODE", type = JAXBElement.class)
    protected JAXBElement<String> gendercode;
    @XmlElementRef(name = "ZIP_CODE", type = JAXBElement.class)
    protected JAXBElement<String> zipcode;
    @XmlElementRef(name = "STATE", type = JAXBElement.class)
    protected JAXBElement<String> state;
    @XmlElementRef(name = "TRANSACTION_DATE_TIME", type = JAXBElement.class)
    protected JAXBElement<String> transactiondatetime;
    @XmlElementRef(name = "COUNTY", type = JAXBElement.class)
    protected JAXBElement<String> county;
    @XmlElementRef(name = "CITY", type = JAXBElement.class)
    protected JAXBElement<String> city;
    @XmlElementRef(name = "COUNTRY", type = JAXBElement.class)
    protected JAXBElement<String> country;
    @XmlElementRef(name = "PCP_OID", type = JAXBElement.class)
    protected JAXBElement<String> pcpoid;
    @XmlElementRef(name = "PCP_NAME", type = JAXBElement.class)
    protected JAXBElement<String> pcpname;
    @XmlElementRef(name = "ETHNICITY_CODE_SYSTEM", type = JAXBElement.class)
    protected JAXBElement<String> ethnicitycodesystem;
    @XmlElementRef(name = "ETHNICITY_CODE_NAME", type = JAXBElement.class)
    protected JAXBElement<String> ethnicitycodename;
    @XmlElementRef(name = "GENDER_CODE_SYSTEM", type = JAXBElement.class)
    protected JAXBElement<String> gendercodesystem;
    @XmlElementRef(name = "PATIENT_EUID", type = JAXBElement.class)
    protected JAXBElement<String> patienteuid;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the facilityid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACILITYID() {
        return facilityid;
    }

    /**
     * Sets the value of the facilityid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACILITYID(String value) {
        this.facilityid = value;
    }

    /**
     * Gets the value of the patientid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPATIENTID() {
        return patientid;
    }

    /**
     * Sets the value of the patientid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPATIENTID(String value) {
        this.patientid = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFIRSTNAME(JAXBElement<String> value) {
        this.firstname = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLASTNAME() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLASTNAME(JAXBElement<String> value) {
        this.lastname = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the middleinitial property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMIDDLEINITIAL() {
        return middleinitial;
    }

    /**
     * Sets the value of the middleinitial property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMIDDLEINITIAL(JAXBElement<String> value) {
        this.middleinitial = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the streetaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSTREETADDRESS1() {
        return streetaddress1;
    }

    /**
     * Sets the value of the streetaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSTREETADDRESS1(JAXBElement<String> value) {
        this.streetaddress1 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the streetaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSTREETADDRESS2() {
        return streetaddress2;
    }

    /**
     * Sets the value of the streetaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSTREETADDRESS2(JAXBElement<String> value) {
        this.streetaddress2 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the telephone property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTELEPHONE() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTELEPHONE(JAXBElement<String> value) {
        this.telephone = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the birthdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBIRTHDATETIME() {
        return birthdatetime;
    }

    /**
     * Sets the value of the birthdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBIRTHDATETIME(JAXBElement<String> value) {
        this.birthdatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the languagecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANGUAGECODE() {
        return languagecode;
    }

    /**
     * Sets the value of the languagecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANGUAGECODE(String value) {
        this.languagecode = value;
    }

    /**
     * Gets the value of the ethnicitycode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getETHNICITYCODE() {
        return ethnicitycode;
    }

    /**
     * Sets the value of the ethnicitycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setETHNICITYCODE(JAXBElement<String> value) {
        this.ethnicitycode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAGE() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAGE(JAXBElement<String> value) {
        this.age = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the ageunits property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAGEUNITS() {
        return ageunits;
    }

    /**
     * Sets the value of the ageunits property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAGEUNITS(JAXBElement<String> value) {
        this.ageunits = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the gendercode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGENDERCODE() {
        return gendercode;
    }

    /**
     * Sets the value of the gendercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGENDERCODE(JAXBElement<String> value) {
        this.gendercode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the zipcode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getZIPCODE() {
        return zipcode;
    }

    /**
     * Sets the value of the zipcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setZIPCODE(JAXBElement<String> value) {
        this.zipcode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSTATE(JAXBElement<String> value) {
        this.state = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the transactiondatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTRANSACTIONDATETIME() {
        return transactiondatetime;
    }

    /**
     * Sets the value of the transactiondatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTRANSACTIONDATETIME(JAXBElement<String> value) {
        this.transactiondatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCOUNTY() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCOUNTY(JAXBElement<String> value) {
        this.county = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCITY(JAXBElement<String> value) {
        this.city = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCOUNTRY() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCOUNTRY(JAXBElement<String> value) {
        this.country = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the pcpoid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPCPOID() {
        return pcpoid;
    }

    /**
     * Sets the value of the pcpoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPCPOID(JAXBElement<String> value) {
        this.pcpoid = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the pcpname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPCPNAME() {
        return pcpname;
    }

    /**
     * Sets the value of the pcpname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPCPNAME(JAXBElement<String> value) {
        this.pcpname = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the ethnicitycodesystem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getETHNICITYCODESYSTEM() {
        return ethnicitycodesystem;
    }

    /**
     * Sets the value of the ethnicitycodesystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setETHNICITYCODESYSTEM(JAXBElement<String> value) {
        this.ethnicitycodesystem = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the ethnicitycodename property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getETHNICITYCODENAME() {
        return ethnicitycodename;
    }

    /**
     * Sets the value of the ethnicitycodename property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setETHNICITYCODENAME(JAXBElement<String> value) {
        this.ethnicitycodename = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the gendercodesystem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGENDERCODESYSTEM() {
        return gendercodesystem;
    }

    /**
     * Sets the value of the gendercodesystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGENDERCODESYSTEM(JAXBElement<String> value) {
        this.gendercodesystem = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the patienteuid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPATIENTEUID() {
        return patienteuid;
    }

    /**
     * Sets the value of the patienteuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPATIENTEUID(JAXBElement<String> value) {
        this.patienteuid = ((JAXBElement<String> ) value);
    }

}
