//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Direct.Config.Client.MonitorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:directproject:config/store/082010", ConfigurationName="MonitorService.IMdnMonitor")]
    public interface IMdnMonitor {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IMdnMonitor/Start", ReplyAction="urn:directproject:config/store/082010/IMdnMonitor/StartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IMdnMonitor/StartConfigStoreFaultFault", Name="ConfigStoreFault")]
        void Start(Health.Direct.Config.Store.Mdn[] mdns);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IMdnMonitor/Update", ReplyAction="urn:directproject:config/store/082010/IMdnMonitor/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IMdnMonitor/UpdateConfigStoreFaultFault", Name="ConfigStoreFault")]
        void Update(Health.Direct.Config.Store.Mdn mdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IMdnMonitor/GetExpiredProcessed", ReplyAction="urn:directproject:config/store/082010/IMdnMonitor/GetExpiredProcessedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IMdnMonitor/GetExpiredProcessedConfigStoreF" +
            "aultFault", Name="ConfigStoreFault")]
        Health.Direct.Config.Store.Mdn[] GetExpiredProcessed(System.TimeSpan expiredLimit, int maxResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IMdnMonitor/GetExpiredDispatched", ReplyAction="urn:directproject:config/store/082010/IMdnMonitor/GetExpiredDispatchedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IMdnMonitor/GetExpiredDispatchedConfigStore" +
            "FaultFault", Name="ConfigStoreFault")]
        Health.Direct.Config.Store.Mdn[] GetExpiredDispatched(System.TimeSpan expiredLimit, int maxResults);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IMdnMonitor/SweepTimouts", ReplyAction="urn:directproject:config/store/082010/IMdnMonitor/SweepTimoutsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IMdnMonitor/SweepTimoutsConfigStoreFaultFau" +
            "lt", Name="ConfigStoreFault")]
        void SweepTimouts(System.TimeSpan expiredLimit, int bulkCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:directproject:config/store/082010/IMdnMonitor/EnumerateMdns", ReplyAction="urn:directproject:config/store/082010/IMdnMonitor/EnumerateMdnsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Health.Direct.Config.Store.ConfigStoreFault), Action="urn:directproject:config/store/082010/IMdnMonitor/EnumerateMdnsConfigStoreFaultFa" +
            "ult", Name="ConfigStoreFault")]
        Health.Direct.Config.Store.Mdn[] EnumerateMdns(string lastMdnName, int maxResults);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMdnMonitorChannel : Health.Direct.Config.Client.MonitorService.IMdnMonitor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MdnMonitorClient : System.ServiceModel.ClientBase<Health.Direct.Config.Client.MonitorService.IMdnMonitor>, Health.Direct.Config.Client.MonitorService.IMdnMonitor {
        
        public MdnMonitorClient() {
        }
        
        public MdnMonitorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MdnMonitorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MdnMonitorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MdnMonitorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Start(Health.Direct.Config.Store.Mdn[] mdns) {
            base.Channel.Start(mdns);
        }
        
        public void Update(Health.Direct.Config.Store.Mdn mdn) {
            base.Channel.Update(mdn);
        }
        
        public Health.Direct.Config.Store.Mdn[] GetExpiredProcessed(System.TimeSpan expiredLimit, int maxResults) {
            return base.Channel.GetExpiredProcessed(expiredLimit, maxResults);
        }
        
        public Health.Direct.Config.Store.Mdn[] GetExpiredDispatched(System.TimeSpan expiredLimit, int maxResults) {
            return base.Channel.GetExpiredDispatched(expiredLimit, maxResults);
        }
        
        public void SweepTimouts(System.TimeSpan expiredLimit, int bulkCount) {
            base.Channel.SweepTimouts(expiredLimit, bulkCount);
        }
        
        public Health.Direct.Config.Store.Mdn[] EnumerateMdns(string lastMdnName, int maxResults) {
            return base.Channel.EnumerateMdns(lastMdnName, maxResults);
        }
    }
}
