/* 
 * Copyright (c) 2010, NHIN Direct Project
 * All rights reserved.
 *  
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright 
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the distribution.  
 * 3. Neither the name of the the NHIN Direct Project (nhindirect.org)
 *    nor the names of its contributors may be used to endorse or promote products 
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.20 at 07:20:23 PM EDT 
//


package org.nhindirect.xd.transform.parse.ccd.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ENCOUNTER_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_INJURY_CODE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_CODE_SYSTEM">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_DISPLAY_NAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_TYPE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RANK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_DATE_TIME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SNOWMED_DIAGNOSIS_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_CODE_DESC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ICD9_DIAGNOSIS_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIAGNOSIS_STATUS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "diagnosisid",
    "encounterid",
    "diagnosisinjurycode",
    "diagnosiscodesystem",
    "diagnosisdisplayname",
    "diagnosistype",
    "rank",
    "diagnosisdatetime",
    "snowmeddiagnosiscode",
    "diagnosiscodedesc",
    "icd9DIAGNOSISCODE",
    "diagnosisstatus"
})
@XmlRootElement(name = "DIAGNOSIS")
public class DIAGNOSIS {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "DIAGNOSIS_ID", required = true)
    protected String diagnosisid;
    @XmlElement(name = "ENCOUNTER_ID", defaultValue = "-1")
    protected int encounterid;
    @XmlElement(name = "DIAGNOSIS_INJURY_CODE", required = true)
    protected String diagnosisinjurycode;
    @XmlElement(name = "DIAGNOSIS_CODE_SYSTEM", required = true)
    protected String diagnosiscodesystem;
    @XmlElement(name = "DIAGNOSIS_DISPLAY_NAME", required = true)
    protected String diagnosisdisplayname;
    @XmlElement(name = "DIAGNOSIS_TYPE", required = true)
    protected String diagnosistype;
    @XmlElementRef(name = "RANK", type = JAXBElement.class)
    protected JAXBElement<String> rank;
    @XmlElement(name = "DIAGNOSIS_DATE_TIME", required = true)
    protected String diagnosisdatetime;
    @XmlElementRef(name = "SNOWMED_DIAGNOSIS_CODE", type = JAXBElement.class)
    protected JAXBElement<String> snowmeddiagnosiscode;
    @XmlElementRef(name = "DIAGNOSIS_CODE_DESC", type = JAXBElement.class)
    protected JAXBElement<String> diagnosiscodedesc;
    @XmlElementRef(name = "ICD9_DIAGNOSIS_CODE", type = JAXBElement.class)
    protected JAXBElement<String> icd9DIAGNOSISCODE;
    @XmlElementRef(name = "DIAGNOSIS_STATUS", type = JAXBElement.class)
    protected JAXBElement<String> diagnosisstatus;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the diagnosisid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIAGNOSISID() {
        return diagnosisid;
    }

    /**
     * Sets the value of the diagnosisid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIAGNOSISID(String value) {
        this.diagnosisid = value;
    }

    /**
     * Gets the value of the encounterid property.
     * 
     */
    public int getENCOUNTERID() {
        return encounterid;
    }

    /**
     * Sets the value of the encounterid property.
     * 
     */
    public void setENCOUNTERID(int value) {
        this.encounterid = value;
    }

    /**
     * Gets the value of the diagnosisinjurycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIAGNOSISINJURYCODE() {
        return diagnosisinjurycode;
    }

    /**
     * Sets the value of the diagnosisinjurycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIAGNOSISINJURYCODE(String value) {
        this.diagnosisinjurycode = value;
    }

    /**
     * Gets the value of the diagnosiscodesystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIAGNOSISCODESYSTEM() {
        return diagnosiscodesystem;
    }

    /**
     * Sets the value of the diagnosiscodesystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIAGNOSISCODESYSTEM(String value) {
        this.diagnosiscodesystem = value;
    }

    /**
     * Gets the value of the diagnosisdisplayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIAGNOSISDISPLAYNAME() {
        return diagnosisdisplayname;
    }

    /**
     * Sets the value of the diagnosisdisplayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIAGNOSISDISPLAYNAME(String value) {
        this.diagnosisdisplayname = value;
    }

    /**
     * Gets the value of the diagnosistype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIAGNOSISTYPE() {
        return diagnosistype;
    }

    /**
     * Sets the value of the diagnosistype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIAGNOSISTYPE(String value) {
        this.diagnosistype = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRANK() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRANK(JAXBElement<String> value) {
        this.rank = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the diagnosisdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIAGNOSISDATETIME() {
        return diagnosisdatetime;
    }

    /**
     * Sets the value of the diagnosisdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIAGNOSISDATETIME(String value) {
        this.diagnosisdatetime = value;
    }

    /**
     * Gets the value of the snowmeddiagnosiscode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSNOWMEDDIAGNOSISCODE() {
        return snowmeddiagnosiscode;
    }

    /**
     * Sets the value of the snowmeddiagnosiscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSNOWMEDDIAGNOSISCODE(JAXBElement<String> value) {
        this.snowmeddiagnosiscode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the diagnosiscodedesc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDIAGNOSISCODEDESC() {
        return diagnosiscodedesc;
    }

    /**
     * Sets the value of the diagnosiscodedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDIAGNOSISCODEDESC(JAXBElement<String> value) {
        this.diagnosiscodedesc = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the icd9DIAGNOSISCODE property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getICD9DIAGNOSISCODE() {
        return icd9DIAGNOSISCODE;
    }

    /**
     * Sets the value of the icd9DIAGNOSISCODE property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setICD9DIAGNOSISCODE(JAXBElement<String> value) {
        this.icd9DIAGNOSISCODE = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the diagnosisstatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDIAGNOSISSTATUS() {
        return diagnosisstatus;
    }

    /**
     * Sets the value of the diagnosisstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDIAGNOSISSTATUS(JAXBElement<String> value) {
        this.diagnosisstatus = ((JAXBElement<String> ) value);
    }

}
