/* 
 * Copyright (c) 2010, NHIN Direct Project
 * All rights reserved.
 *  
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright 
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the distribution.  
 * 3. Neither the name of the the NHIN Direct Project (nhindirect.org)
 *    nor the names of its contributors may be used to endorse or promote products 
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.20 at 07:20:23 PM EDT 
//


package org.nhindirect.xd.transform.parse.ccd.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ENCOUNTER_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FACILITY_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VISIT_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PATIENT_ID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LAST_UPDATE_DATE_TIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PATIENT_CLASS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CHIEF_COMPLAINT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SYMPTOM_ILLNESS_ONSET_DATETIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *               &lt;minInclusive value="1000-01-01T00:00:00"/>
 *               &lt;maxInclusive value="9999-12-31T23:59:59"/>
 *               &lt;pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}T\p{Nd}{2}:\p{Nd}{2}:\p{Nd}{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ADM_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ADM_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ADM_ENC_DATE_TIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DISCHARGE_DATE_TIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DISCHARGE_DISPOSITION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DISCHARGE_DIAG_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ADMISSION_DIAG_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "encounterid",
    "facilityid",
    "visitid",
    "patientid",
    "lastupdatedatetime",
    "patientclass",
    "chiefcomplaint",
    "symptomillnessonsetdatetime",
    "admcode",
    "admtype",
    "admencdatetime",
    "dischargedatetime",
    "dischargedisposition",
    "dischargediagcode",
    "admissiondiagcode"
})
@XmlRootElement(name = "ENCOUNTER")
public class ENCOUNTER {

    @XmlElement(name = "ENCOUNTER_ID")
    protected int encounterid;
    @XmlElement(name = "FACILITY_ID", required = true)
    protected String facilityid;
    @XmlElement(name = "VISIT_ID", required = true)
    protected String visitid;
    @XmlElementRef(name = "PATIENT_ID", type = JAXBElement.class)
    protected JAXBElement<Integer> patientid;
    @XmlElementRef(name = "LAST_UPDATE_DATE_TIME", type = JAXBElement.class)
    protected JAXBElement<String> lastupdatedatetime;
    @XmlElementRef(name = "PATIENT_CLASS", type = JAXBElement.class)
    protected JAXBElement<String> patientclass;
    @XmlElementRef(name = "CHIEF_COMPLAINT", type = JAXBElement.class)
    protected JAXBElement<String> chiefcomplaint;
    @XmlElementRef(name = "SYMPTOM_ILLNESS_ONSET_DATETIME", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> symptomillnessonsetdatetime;
    @XmlElementRef(name = "ADM_CODE", type = JAXBElement.class)
    protected JAXBElement<String> admcode;
    @XmlElementRef(name = "ADM_TYPE", type = JAXBElement.class)
    protected JAXBElement<String> admtype;
    @XmlElementRef(name = "ADM_ENC_DATE_TIME", type = JAXBElement.class)
    protected JAXBElement<String> admencdatetime;
    @XmlElementRef(name = "DISCHARGE_DATE_TIME", type = JAXBElement.class)
    protected JAXBElement<String> dischargedatetime;
    @XmlElementRef(name = "DISCHARGE_DISPOSITION", type = JAXBElement.class)
    protected JAXBElement<String> dischargedisposition;
    @XmlElementRef(name = "DISCHARGE_DIAG_CODE", type = JAXBElement.class)
    protected JAXBElement<String> dischargediagcode;
    @XmlElementRef(name = "ADMISSION_DIAG_CODE", type = JAXBElement.class)
    protected JAXBElement<String> admissiondiagcode;

    /**
     * Gets the value of the encounterid property.
     * 
     */
    public int getENCOUNTERID() {
        return encounterid;
    }

    /**
     * Sets the value of the encounterid property.
     * 
     */
    public void setENCOUNTERID(int value) {
        this.encounterid = value;
    }

    /**
     * Gets the value of the facilityid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACILITYID() {
        return facilityid;
    }

    /**
     * Sets the value of the facilityid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACILITYID(String value) {
        this.facilityid = value;
    }

    /**
     * Gets the value of the visitid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVISITID() {
        return visitid;
    }

    /**
     * Sets the value of the visitid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVISITID(String value) {
        this.visitid = value;
    }

    /**
     * Gets the value of the patientid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getPATIENTID() {
        return patientid;
    }

    /**
     * Sets the value of the patientid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setPATIENTID(JAXBElement<Integer> value) {
        this.patientid = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the lastupdatedatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLASTUPDATEDATETIME() {
        return lastupdatedatetime;
    }

    /**
     * Sets the value of the lastupdatedatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLASTUPDATEDATETIME(JAXBElement<String> value) {
        this.lastupdatedatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the patientclass property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPATIENTCLASS() {
        return patientclass;
    }

    /**
     * Sets the value of the patientclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPATIENTCLASS(JAXBElement<String> value) {
        this.patientclass = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the chiefcomplaint property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCHIEFCOMPLAINT() {
        return chiefcomplaint;
    }

    /**
     * Sets the value of the chiefcomplaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCHIEFCOMPLAINT(JAXBElement<String> value) {
        this.chiefcomplaint = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the symptomillnessonsetdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getSYMPTOMILLNESSONSETDATETIME() {
        return symptomillnessonsetdatetime;
    }

    /**
     * Sets the value of the symptomillnessonsetdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setSYMPTOMILLNESSONSETDATETIME(JAXBElement<XMLGregorianCalendar> value) {
        this.symptomillnessonsetdatetime = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the admcode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getADMCODE() {
        return admcode;
    }

    /**
     * Sets the value of the admcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setADMCODE(JAXBElement<String> value) {
        this.admcode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the admtype property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getADMTYPE() {
        return admtype;
    }

    /**
     * Sets the value of the admtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setADMTYPE(JAXBElement<String> value) {
        this.admtype = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the admencdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getADMENCDATETIME() {
        return admencdatetime;
    }

    /**
     * Sets the value of the admencdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setADMENCDATETIME(JAXBElement<String> value) {
        this.admencdatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dischargedatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDISCHARGEDATETIME() {
        return dischargedatetime;
    }

    /**
     * Sets the value of the dischargedatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDISCHARGEDATETIME(JAXBElement<String> value) {
        this.dischargedatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dischargedisposition property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDISCHARGEDISPOSITION() {
        return dischargedisposition;
    }

    /**
     * Sets the value of the dischargedisposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDISCHARGEDISPOSITION(JAXBElement<String> value) {
        this.dischargedisposition = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dischargediagcode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDISCHARGEDIAGCODE() {
        return dischargediagcode;
    }

    /**
     * Sets the value of the dischargediagcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDISCHARGEDIAGCODE(JAXBElement<String> value) {
        this.dischargediagcode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the admissiondiagcode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getADMISSIONDIAGCODE() {
        return admissiondiagcode;
    }

    /**
     * Sets the value of the admissiondiagcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setADMISSIONDIAGCODE(JAXBElement<String> value) {
        this.admissiondiagcode = ((JAXBElement<String> ) value);
    }

}
