/* 
 * Copyright (c) 2010, NHIN Direct Project
 * All rights reserved.
 *  
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright 
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the distribution.  
 * 3. Neither the name of the the NHIN Direct Project (nhindirect.org)
 *    nor the names of its contributors may be used to endorse or promote products 
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.20 at 07:20:23 PM EDT 
//


package org.nhindirect.xd.transform.parse.ccd.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ENCOUNTER_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long">
 *               &lt;minInclusive value="-2147483648"/>
 *               &lt;maxInclusive value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OBSERVATION_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORDER_NUMBER">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REPORTING_LAB_IDENTIFIER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PERFORMING_LAB" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REPORT_DATE_TIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESULT_STATUS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="COLLECTION_DATE_TIME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SPECIMEN_SOURCE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OBSERVATION_CODE_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OBSERVATION_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OBSERVATION_NAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESULT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESULT_TYPE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESULT_UNIT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="METHOD_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TEST_INTERPRETATION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TEST_INTERPRETATION_SYSTEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SPECIMEN_ID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORDERED_TEST_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORDERED_TEST_ID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORGANISM_IDENTIFIED" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUSCEPTIBILITY_TEST_INTERPRETATION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TEST_STATUS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "encounterid",
    "observationid",
    "ordernumber",
    "reportinglabidentifier",
    "performinglab",
    "reportdatetime",
    "resultstatus",
    "collectiondatetime",
    "specimensource",
    "observationcodetype",
    "observationcode",
    "observationname",
    "result",
    "resulttype",
    "resultunit",
    "methodtype",
    "testinterpretation",
    "testinterpretationsystem",
    "specimenid",
    "orderedtestname",
    "orderedtestid",
    "organismidentified",
    "susceptibilitytestinterpretation",
    "teststatus"
})
@XmlRootElement(name = "TEST_RESULT")
public class TESTRESULT {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "ENCOUNTER_ID", defaultValue = "-1")
    protected int encounterid;
    @XmlElement(name = "OBSERVATION_ID", required = true)
    protected String observationid;
    @XmlElement(name = "ORDER_NUMBER", required = true)
    protected String ordernumber;
    @XmlElementRef(name = "REPORTING_LAB_IDENTIFIER", type = JAXBElement.class)
    protected JAXBElement<String> reportinglabidentifier;
    @XmlElementRef(name = "PERFORMING_LAB", type = JAXBElement.class)
    protected JAXBElement<String> performinglab;
    @XmlElementRef(name = "REPORT_DATE_TIME", type = JAXBElement.class)
    protected JAXBElement<String> reportdatetime;
    @XmlElementRef(name = "RESULT_STATUS", type = JAXBElement.class)
    protected JAXBElement<String> resultstatus;
    @XmlElementRef(name = "COLLECTION_DATE_TIME", type = JAXBElement.class)
    protected JAXBElement<String> collectiondatetime;
    @XmlElementRef(name = "SPECIMEN_SOURCE", type = JAXBElement.class)
    protected JAXBElement<String> specimensource;
    @XmlElementRef(name = "OBSERVATION_CODE_TYPE", type = JAXBElement.class)
    protected JAXBElement<String> observationcodetype;
    @XmlElementRef(name = "OBSERVATION_CODE", type = JAXBElement.class)
    protected JAXBElement<String> observationcode;
    @XmlElement(name = "OBSERVATION_NAME", required = true)
    protected String observationname;
    @XmlElementRef(name = "RESULT", type = JAXBElement.class)
    protected JAXBElement<String> result;
    @XmlElement(name = "RESULT_TYPE", required = true)
    protected String resulttype;
    @XmlElementRef(name = "RESULT_UNIT", type = JAXBElement.class)
    protected JAXBElement<String> resultunit;
    @XmlElementRef(name = "METHOD_TYPE", type = JAXBElement.class)
    protected JAXBElement<String> methodtype;
    @XmlElementRef(name = "TEST_INTERPRETATION", type = JAXBElement.class)
    protected JAXBElement<String> testinterpretation;
    @XmlElementRef(name = "TEST_INTERPRETATION_SYSTEM", type = JAXBElement.class)
    protected JAXBElement<String> testinterpretationsystem;
    @XmlElementRef(name = "SPECIMEN_ID", type = JAXBElement.class)
    protected JAXBElement<String> specimenid;
    @XmlElementRef(name = "ORDERED_TEST_NAME", type = JAXBElement.class)
    protected JAXBElement<String> orderedtestname;
    @XmlElementRef(name = "ORDERED_TEST_ID", type = JAXBElement.class)
    protected JAXBElement<String> orderedtestid;
    @XmlElementRef(name = "ORGANISM_IDENTIFIED", type = JAXBElement.class)
    protected JAXBElement<String> organismidentified;
    @XmlElementRef(name = "SUSCEPTIBILITY_TEST_INTERPRETATION", type = JAXBElement.class)
    protected JAXBElement<String> susceptibilitytestinterpretation;
    @XmlElementRef(name = "TEST_STATUS", type = JAXBElement.class)
    protected JAXBElement<String> teststatus;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the encounterid property.
     * 
     */
    public int getENCOUNTERID() {
        return encounterid;
    }

    /**
     * Sets the value of the encounterid property.
     * 
     */
    public void setENCOUNTERID(int value) {
        this.encounterid = value;
    }

    /**
     * Gets the value of the observationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBSERVATIONID() {
        return observationid;
    }

    /**
     * Sets the value of the observationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBSERVATIONID(String value) {
        this.observationid = value;
    }

    /**
     * Gets the value of the ordernumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERNUMBER() {
        return ordernumber;
    }

    /**
     * Sets the value of the ordernumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERNUMBER(String value) {
        this.ordernumber = value;
    }

    /**
     * Gets the value of the reportinglabidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getREPORTINGLABIDENTIFIER() {
        return reportinglabidentifier;
    }

    /**
     * Sets the value of the reportinglabidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setREPORTINGLABIDENTIFIER(JAXBElement<String> value) {
        this.reportinglabidentifier = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the performinglab property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPERFORMINGLAB() {
        return performinglab;
    }

    /**
     * Sets the value of the performinglab property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPERFORMINGLAB(JAXBElement<String> value) {
        this.performinglab = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the reportdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getREPORTDATETIME() {
        return reportdatetime;
    }

    /**
     * Sets the value of the reportdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setREPORTDATETIME(JAXBElement<String> value) {
        this.reportdatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the resultstatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRESULTSTATUS() {
        return resultstatus;
    }

    /**
     * Sets the value of the resultstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRESULTSTATUS(JAXBElement<String> value) {
        this.resultstatus = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the collectiondatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCOLLECTIONDATETIME() {
        return collectiondatetime;
    }

    /**
     * Sets the value of the collectiondatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCOLLECTIONDATETIME(JAXBElement<String> value) {
        this.collectiondatetime = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the specimensource property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSPECIMENSOURCE() {
        return specimensource;
    }

    /**
     * Sets the value of the specimensource property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSPECIMENSOURCE(JAXBElement<String> value) {
        this.specimensource = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the observationcodetype property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOBSERVATIONCODETYPE() {
        return observationcodetype;
    }

    /**
     * Sets the value of the observationcodetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOBSERVATIONCODETYPE(JAXBElement<String> value) {
        this.observationcodetype = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the observationcode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOBSERVATIONCODE() {
        return observationcode;
    }

    /**
     * Sets the value of the observationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOBSERVATIONCODE(JAXBElement<String> value) {
        this.observationcode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the observationname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBSERVATIONNAME() {
        return observationname;
    }

    /**
     * Sets the value of the observationname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBSERVATIONNAME(String value) {
        this.observationname = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRESULT() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRESULT(JAXBElement<String> value) {
        this.result = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the resulttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESULTTYPE() {
        return resulttype;
    }

    /**
     * Sets the value of the resulttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESULTTYPE(String value) {
        this.resulttype = value;
    }

    /**
     * Gets the value of the resultunit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRESULTUNIT() {
        return resultunit;
    }

    /**
     * Sets the value of the resultunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRESULTUNIT(JAXBElement<String> value) {
        this.resultunit = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the methodtype property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMETHODTYPE() {
        return methodtype;
    }

    /**
     * Sets the value of the methodtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMETHODTYPE(JAXBElement<String> value) {
        this.methodtype = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the testinterpretation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTESTINTERPRETATION() {
        return testinterpretation;
    }

    /**
     * Sets the value of the testinterpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTESTINTERPRETATION(JAXBElement<String> value) {
        this.testinterpretation = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the testinterpretationsystem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTESTINTERPRETATIONSYSTEM() {
        return testinterpretationsystem;
    }

    /**
     * Sets the value of the testinterpretationsystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTESTINTERPRETATIONSYSTEM(JAXBElement<String> value) {
        this.testinterpretationsystem = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the specimenid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSPECIMENID() {
        return specimenid;
    }

    /**
     * Sets the value of the specimenid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSPECIMENID(JAXBElement<String> value) {
        this.specimenid = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the orderedtestname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getORDEREDTESTNAME() {
        return orderedtestname;
    }

    /**
     * Sets the value of the orderedtestname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setORDEREDTESTNAME(JAXBElement<String> value) {
        this.orderedtestname = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the orderedtestid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getORDEREDTESTID() {
        return orderedtestid;
    }

    /**
     * Sets the value of the orderedtestid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setORDEREDTESTID(JAXBElement<String> value) {
        this.orderedtestid = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the organismidentified property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getORGANISMIDENTIFIED() {
        return organismidentified;
    }

    /**
     * Sets the value of the organismidentified property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setORGANISMIDENTIFIED(JAXBElement<String> value) {
        this.organismidentified = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the susceptibilitytestinterpretation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSUSCEPTIBILITYTESTINTERPRETATION() {
        return susceptibilitytestinterpretation;
    }

    /**
     * Sets the value of the susceptibilitytestinterpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSUSCEPTIBILITYTESTINTERPRETATION(JAXBElement<String> value) {
        this.susceptibilitytestinterpretation = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the teststatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTESTSTATUS() {
        return teststatus;
    }

    /**
     * Sets the value of the teststatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTESTSTATUS(JAXBElement<String> value) {
        this.teststatus = ((JAXBElement<String> ) value);
    }

}
