/* 
 * Copyright (c) 2010, NHIN Direct Project
 * All rights reserved.
 *  
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright 
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the distribution.  
 * 3. Neither the name of the the NHIN Direct Project (nhindirect.org)
 *    nor the names of its contributors may be used to endorse or promote products 
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.20 at 07:20:23 PM EDT 
//


package org.nhindirect.transform.parse.ccd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CLINICAL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}DIAGNOSIS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ENCOUNTER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}EVENT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}FACILITY" maxOccurs="unbounded"/>
 *         &lt;element ref="{}IMMUNIZATION" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PATIENT"/>
 *         &lt;element ref="{}PROCEDURES" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PROVIDER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}REPRESENTED_ORGANIZATION" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SUBSTANCE_ADMIN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}TEST_RESULT" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clinical",
    "diagnosis",
    "encounter",
    "event",
    "facility",
    "immunization",
    "patient",
    "procedures",
    "provider",
    "representedorganization",
    "substanceadmin",
    "testresult"
})
@XmlRootElement(name = "CCDDB")
public class CCDDB {

    @XmlElement(name = "CLINICAL")
    protected List<CLINICAL> clinical;
    @XmlElement(name = "DIAGNOSIS")
    protected List<DIAGNOSIS> diagnosis;
    @XmlElement(name = "ENCOUNTER")
    protected List<ENCOUNTER> encounter;
    @XmlElement(name = "EVENT")
    protected List<EVENT> event;
    @XmlElement(name = "FACILITY", required = true)
    protected List<FACILITY> facility;
    @XmlElement(name = "IMMUNIZATION")
    protected List<IMMUNIZATION> immunization;
    @XmlElement(name = "PATIENT", required = true)
    protected PATIENT patient;
    @XmlElement(name = "PROCEDURES")
    protected List<PROCEDURES> procedures;
    @XmlElement(name = "PROVIDER")
    protected List<PROVIDER> provider;
    @XmlElement(name = "REPRESENTED_ORGANIZATION")
    protected List<REPRESENTEDORGANIZATION> representedorganization;
    @XmlElement(name = "SUBSTANCE_ADMIN")
    protected List<SUBSTANCEADMIN> substanceadmin;
    @XmlElement(name = "TEST_RESULT")
    protected List<TESTRESULT> testresult;

    /**
     * Gets the value of the clinical property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clinical property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCLINICAL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CLINICAL }
     * 
     * 
     */
    public List<CLINICAL> getCLINICAL() {
        if (clinical == null) {
            clinical = new ArrayList<CLINICAL>();
        }
        return this.clinical;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDIAGNOSIS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DIAGNOSIS }
     * 
     * 
     */
    public List<DIAGNOSIS> getDIAGNOSIS() {
        if (diagnosis == null) {
            diagnosis = new ArrayList<DIAGNOSIS>();
        }
        return this.diagnosis;
    }

    /**
     * Gets the value of the encounter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encounter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getENCOUNTER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ENCOUNTER }
     * 
     * 
     */
    public List<ENCOUNTER> getENCOUNTER() {
        if (encounter == null) {
            encounter = new ArrayList<ENCOUNTER>();
        }
        return this.encounter;
    }

    /**
     * Gets the value of the event property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEVENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EVENT }
     * 
     * 
     */
    public List<EVENT> getEVENT() {
        if (event == null) {
            event = new ArrayList<EVENT>();
        }
        return this.event;
    }

    /**
     * Gets the value of the facility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFACILITY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FACILITY }
     * 
     * 
     */
    public List<FACILITY> getFACILITY() {
        if (facility == null) {
            facility = new ArrayList<FACILITY>();
        }
        return this.facility;
    }

    /**
     * Gets the value of the immunization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the immunization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIMMUNIZATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IMMUNIZATION }
     * 
     * 
     */
    public List<IMMUNIZATION> getIMMUNIZATION() {
        if (immunization == null) {
            immunization = new ArrayList<IMMUNIZATION>();
        }
        return this.immunization;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link PATIENT }
     *     
     */
    public PATIENT getPATIENT() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link PATIENT }
     *     
     */
    public void setPATIENT(PATIENT value) {
        this.patient = value;
    }

    /**
     * Gets the value of the procedures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the procedures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPROCEDURES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PROCEDURES }
     * 
     * 
     */
    public List<PROCEDURES> getPROCEDURES() {
        if (procedures == null) {
            procedures = new ArrayList<PROCEDURES>();
        }
        return this.procedures;
    }

    /**
     * Gets the value of the provider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the provider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPROVIDER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PROVIDER }
     * 
     * 
     */
    public List<PROVIDER> getPROVIDER() {
        if (provider == null) {
            provider = new ArrayList<PROVIDER>();
        }
        return this.provider;
    }

    /**
     * Gets the value of the representedorganization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the representedorganization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREPRESENTEDORGANIZATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REPRESENTEDORGANIZATION }
     * 
     * 
     */
    public List<REPRESENTEDORGANIZATION> getREPRESENTEDORGANIZATION() {
        if (representedorganization == null) {
            representedorganization = new ArrayList<REPRESENTEDORGANIZATION>();
        }
        return this.representedorganization;
    }

    /**
     * Gets the value of the substanceadmin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substanceadmin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSUBSTANCEADMIN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SUBSTANCEADMIN }
     * 
     * 
     */
    public List<SUBSTANCEADMIN> getSUBSTANCEADMIN() {
        if (substanceadmin == null) {
            substanceadmin = new ArrayList<SUBSTANCEADMIN>();
        }
        return this.substanceadmin;
    }

    /**
     * Gets the value of the testresult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testresult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTESTRESULT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TESTRESULT }
     * 
     * 
     */
    public List<TESTRESULT> getTESTRESULT() {
        if (testresult == null) {
            testresult = new ArrayList<TESTRESULT>();
        }
        return this.testresult;
    }

}
