/* 
 * Copyright (c) 2010, NHIN Direct Project
 * All rights reserved.
 *  
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright 
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the distribution.  
 * 3. Neither the name of the the NHIN Direct Project (nhindirect.org)
 *    nor the names of its contributors may be used to endorse or promote products 
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.20 at 07:20:23 PM EDT 
//


package org.nhindirect.transform.parse.ccd.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gsi.ccddb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _REPRESENTEDORGANIZATIONORGANIZATIONNAME_QNAME = new QName("", "ORGANIZATION_NAME");
    private final static QName _CLINICALMEASUREDATEVALUE_QNAME = new QName("", "MEASURE_DATE_VALUE");
    private final static QName _IMMUNIZATIONROUTECODE_QNAME = new QName("", "ROUTE_CODE");
    private final static QName _IMMUNIZATIONMATERIALCODEDISPLAYNAME_QNAME = new QName("", "MATERIAL_CODE_DISPLAY_NAME");
    private final static QName _IMMUNIZATIONDOSEQUANTITY_QNAME = new QName("", "DOSE_QUANTITY");
    private final static QName _IMMUNIZATIONROUTECODEDISPLAYNAME_QNAME = new QName("", "ROUTE_CODE_DISPLAY_NAME");
    private final static QName _IMMUNIZATIONMATERIALCODESYSTEM_QNAME = new QName("", "MATERIAL_CODE_SYSTEM");
    private final static QName _IMMUNIZATIONDOSEPERIODVALUE_QNAME = new QName("", "DOSE_PERIOD_VALUE");
    private final static QName _IMMUNIZATIONROUTECODESYSTEMNAME_QNAME = new QName("", "ROUTE_CODE_SYSTEM_NAME");
    private final static QName _IMMUNIZATIONDOSEPERIODUNIT_QNAME = new QName("", "DOSE_PERIOD_UNIT");
    private final static QName _IMMUNIZATIONMATERIALCODE_QNAME = new QName("", "MATERIAL_CODE");
    private final static QName _IMMUNIZATIONROUTECODESYSTEM_QNAME = new QName("", "ROUTE_CODE_SYSTEM");
    private final static QName _IMMUNIZATIONDOSEUNIT_QNAME = new QName("", "DOSE_UNIT");
    private final static QName _IMMUNIZATIONSTATUSCODE_QNAME = new QName("", "STATUS_CODE");
    private final static QName _IMMUNIZATIONEFFECTIVEDATETIME_QNAME = new QName("", "EFFECTIVE_DATE_TIME");
    private final static QName _TESTRESULTORDEREDTESTID_QNAME = new QName("", "ORDERED_TEST_ID");
    private final static QName _TESTRESULTORGANISMIDENTIFIED_QNAME = new QName("", "ORGANISM_IDENTIFIED");
    private final static QName _TESTRESULTOBSERVATIONCODETYPE_QNAME = new QName("", "OBSERVATION_CODE_TYPE");
    private final static QName _TESTRESULTTESTINTERPRETATION_QNAME = new QName("", "TEST_INTERPRETATION");
    private final static QName _TESTRESULTPERFORMINGLAB_QNAME = new QName("", "PERFORMING_LAB");
    private final static QName _TESTRESULTOBSERVATIONCODE_QNAME = new QName("", "OBSERVATION_CODE");
    private final static QName _TESTRESULTSPECIMENID_QNAME = new QName("", "SPECIMEN_ID");
    private final static QName _TESTRESULTRESULT_QNAME = new QName("", "RESULT");
    private final static QName _TESTRESULTRESULTUNIT_QNAME = new QName("", "RESULT_UNIT");
    private final static QName _TESTRESULTSPECIMENSOURCE_QNAME = new QName("", "SPECIMEN_SOURCE");
    private final static QName _TESTRESULTTESTSTATUS_QNAME = new QName("", "TEST_STATUS");
    private final static QName _TESTRESULTREPORTINGLABIDENTIFIER_QNAME = new QName("", "REPORTING_LAB_IDENTIFIER");
    private final static QName _TESTRESULTCOLLECTIONDATETIME_QNAME = new QName("", "COLLECTION_DATE_TIME");
    private final static QName _TESTRESULTSUSCEPTIBILITYTESTINTERPRETATION_QNAME = new QName("", "SUSCEPTIBILITY_TEST_INTERPRETATION");
    private final static QName _TESTRESULTREPORTDATETIME_QNAME = new QName("", "REPORT_DATE_TIME");
    private final static QName _TESTRESULTORDEREDTESTNAME_QNAME = new QName("", "ORDERED_TEST_NAME");
    private final static QName _TESTRESULTRESULTSTATUS_QNAME = new QName("", "RESULT_STATUS");
    private final static QName _TESTRESULTTESTINTERPRETATIONSYSTEM_QNAME = new QName("", "TEST_INTERPRETATION_SYSTEM");
    private final static QName _TESTRESULTMETHODTYPE_QNAME = new QName("", "METHOD_TYPE");
    private final static QName _TESTORDERORDERDATETIME_QNAME = new QName("", "ORDER_DATE_TIME");
    private final static QName _TESTORDERTESTPROCEDURECODE_QNAME = new QName("", "TEST_PROCEDURE_CODE");
    private final static QName _TESTORDERTESTPROCEDURENAME_QNAME = new QName("", "TEST_PROCEDURE_NAME");
    private final static QName _TESTORDERTESTPROCEDURECODETYPE_QNAME = new QName("", "TEST_PROCEDURE_CODE_TYPE");
    private final static QName _FACILITYDEATHSINLAST24HOURS_QNAME = new QName("", "DEATHS_IN_LAST_24_HOURS");
    private final static QName _FACILITYNUMBEROFBEDS_QNAME = new QName("", "NUMBER_OF_BEDS");
    private final static QName _FACILITYLASTUPDATEDATETIME_QNAME = new QName("", "LAST_UPDATE_DATETIME");
    private final static QName _FACILITYNUMBEROFROOMS_QNAME = new QName("", "NUMBER_OF_ROOMS");
    private final static QName _FACILITYDISCHARGESLAST24HOURS_QNAME = new QName("", "DISCHARGES_LAST_24_HOURS");
    private final static QName _FACILITYSENDINGFACILITYID_QNAME = new QName("", "SENDING_FACILITY_ID");
    private final static QName _FACILITYADMISSIONSLAST24HOURS_QNAME = new QName("", "ADMISSIONS_LAST_24_HOURS");
    private final static QName _PROCEDURESPROCEDURECODEDISPLAYNAME_QNAME = new QName("", "PROCEDURE_CODE_DISPLAY_NAME");
    private final static QName _PROCEDURESPROCEDURECODESYSTEM_QNAME = new QName("", "PROCEDURE_CODE_SYSTEM");
    private final static QName _PROVIDERPROVIDEREUID_QNAME = new QName("", "PROVIDER_EUID");
    private final static QName _PROVIDERFUNCTIONCODENAME_QNAME = new QName("", "FUNCTION_CODE_NAME");
    private final static QName _PROVIDERFUNCTIONCODE_QNAME = new QName("", "FUNCTION_CODE");
    private final static QName _PROVIDERPERSONPREFIX_QNAME = new QName("", "PERSON_PREFIX");
    private final static QName _PROVIDERPERSONFIRSTNAME_QNAME = new QName("", "PERSON_FIRST_NAME");
    private final static QName _PROVIDERPERSONLASTNAME_QNAME = new QName("", "PERSON_LAST_NAME");
    private final static QName _PROVIDERORGANIZATIONOID_QNAME = new QName("", "ORGANIZATION_OID");
    private final static QName _PROVIDEREVENTENDDATETIME_QNAME = new QName("", "EVENT_END_DATE_TIME");
    private final static QName _PROVIDERFUNCTIONCODESYSTEM_QNAME = new QName("", "FUNCTION_CODE_SYSTEM");
    private final static QName _PROVIDERSOFTWARENAME_QNAME = new QName("", "SOFTWARE_NAME");
    private final static QName _DIAGNOSISSNOWMEDDIAGNOSISCODE_QNAME = new QName("", "SNOWMED_DIAGNOSIS_CODE");
    private final static QName _DIAGNOSISRANK_QNAME = new QName("", "RANK");
    private final static QName _DIAGNOSISDIAGNOSISSTATUS_QNAME = new QName("", "DIAGNOSIS_STATUS");
    private final static QName _DIAGNOSISICD9DIAGNOSISCODE_QNAME = new QName("", "ICD9_DIAGNOSIS_CODE");
    private final static QName _DIAGNOSISDIAGNOSISCODEDESC_QNAME = new QName("", "DIAGNOSIS_CODE_DESC");
    private final static QName _ENCOUNTERPATIENTID_QNAME = new QName("", "PATIENT_ID");
    private final static QName _ENCOUNTERDISCHARGEDIAGCODE_QNAME = new QName("", "DISCHARGE_DIAG_CODE");
    private final static QName _ENCOUNTERSYMPTOMILLNESSONSETDATETIME_QNAME = new QName("", "SYMPTOM_ILLNESS_ONSET_DATETIME");
    private final static QName _ENCOUNTERLASTUPDATEDATETIME_QNAME = new QName("", "LAST_UPDATE_DATE_TIME");
    private final static QName _ENCOUNTERADMENCDATETIME_QNAME = new QName("", "ADM_ENC_DATE_TIME");
    private final static QName _ENCOUNTERCHIEFCOMPLAINT_QNAME = new QName("", "CHIEF_COMPLAINT");
    private final static QName _ENCOUNTERADMTYPE_QNAME = new QName("", "ADM_TYPE");
    private final static QName _ENCOUNTERADMCODE_QNAME = new QName("", "ADM_CODE");
    private final static QName _ENCOUNTERDISCHARGEDISPOSITION_QNAME = new QName("", "DISCHARGE_DISPOSITION");
    private final static QName _ENCOUNTERDISCHARGEDATETIME_QNAME = new QName("", "DISCHARGE_DATE_TIME");
    private final static QName _ENCOUNTERPATIENTCLASS_QNAME = new QName("", "PATIENT_CLASS");
    private final static QName _ENCOUNTERADMISSIONDIAGCODE_QNAME = new QName("", "ADMISSION_DIAG_CODE");
    private final static QName _PATIENTETHNICITYCODESYSTEM_QNAME = new QName("", "ETHNICITY_CODE_SYSTEM");
    private final static QName _PATIENTGENDERCODESYSTEM_QNAME = new QName("", "GENDER_CODE_SYSTEM");
    private final static QName _PATIENTAGEUNITS_QNAME = new QName("", "AGE_UNITS");
    private final static QName _PATIENTZIPCODE_QNAME = new QName("", "ZIP_CODE");
    private final static QName _PATIENTSTATE_QNAME = new QName("", "STATE");
    private final static QName _PATIENTAGE_QNAME = new QName("", "AGE");
    private final static QName _PATIENTCOUNTRY_QNAME = new QName("", "COUNTRY");
    private final static QName _PATIENTETHNICITYCODE_QNAME = new QName("", "ETHNICITY_CODE");
    private final static QName _PATIENTPCPOID_QNAME = new QName("", "PCP_OID");
    private final static QName _PATIENTPATIENTEUID_QNAME = new QName("", "PATIENT_EUID");
    private final static QName _PATIENTTELEPHONE_QNAME = new QName("", "TELEPHONE");
    private final static QName _PATIENTLASTNAME_QNAME = new QName("", "LAST_NAME");
    private final static QName _PATIENTCOUNTY_QNAME = new QName("", "COUNTY");
    private final static QName _PATIENTPCPNAME_QNAME = new QName("", "PCP_NAME");
    private final static QName _PATIENTTRANSACTIONDATETIME_QNAME = new QName("", "TRANSACTION_DATE_TIME");
    private final static QName _PATIENTMIDDLEINITIAL_QNAME = new QName("", "MIDDLE_INITIAL");
    private final static QName _PATIENTFIRSTNAME_QNAME = new QName("", "FIRST_NAME");
    private final static QName _PATIENTSTREETADDRESS2_QNAME = new QName("", "STREET_ADDRESS_2");
    private final static QName _PATIENTETHNICITYCODENAME_QNAME = new QName("", "ETHNICITY_CODE_NAME");
    private final static QName _PATIENTSTREETADDRESS1_QNAME = new QName("", "STREET_ADDRESS_1");
    private final static QName _PATIENTGENDERCODE_QNAME = new QName("", "GENDER_CODE");
    private final static QName _PATIENTCITY_QNAME = new QName("", "CITY");
    private final static QName _PATIENTBIRTHDATETIME_QNAME = new QName("", "BIRTH_DATE_TIME");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gsi.ccddb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link REPRESENTEDORGANIZATION }
     * 
     */
    public REPRESENTEDORGANIZATION createREPRESENTEDORGANIZATION() {
        return new REPRESENTEDORGANIZATION();
    }

    /**
     * Create an instance of {@link CCDDB }
     * 
     */
    public CCDDB createCCDDB() {
        return new CCDDB();
    }

    /**
     * Create an instance of {@link CLINICAL }
     * 
     */
    public CLINICAL createCLINICAL() {
        return new CLINICAL();
    }

    /**
     * Create an instance of {@link IMMUNIZATION }
     * 
     */
    public IMMUNIZATION createIMMUNIZATION() {
        return new IMMUNIZATION();
    }

    /**
     * Create an instance of {@link TESTRESULT }
     * 
     */
    public TESTRESULT createTESTRESULT() {
        return new TESTRESULT();
    }

    /**
     * Create an instance of {@link EVENT }
     * 
     */
    public EVENT createEVENT() {
        return new EVENT();
    }

    /**
     * Create an instance of {@link TESTORDER }
     * 
     */
    public TESTORDER createTESTORDER() {
        return new TESTORDER();
    }

    /**
     * Create an instance of {@link FACILITY }
     * 
     */
    public FACILITY createFACILITY() {
        return new FACILITY();
    }

    /**
     * Create an instance of {@link PROCEDURES }
     * 
     */
    public PROCEDURES createPROCEDURES() {
        return new PROCEDURES();
    }

    /**
     * Create an instance of {@link PROVIDER }
     * 
     */
    public PROVIDER createPROVIDER() {
        return new PROVIDER();
    }

    /**
     * Create an instance of {@link DIAGNOSIS }
     * 
     */
    public DIAGNOSIS createDIAGNOSIS() {
        return new DIAGNOSIS();
    }

    /**
     * Create an instance of {@link ENCOUNTER }
     * 
     */
    public ENCOUNTER createENCOUNTER() {
        return new ENCOUNTER();
    }

    /**
     * Create an instance of {@link PATIENT }
     * 
     */
    public PATIENT createPATIENT() {
        return new PATIENT();
    }

    /**
     * Create an instance of {@link SUBSTANCEADMIN }
     * 
     */
    public SUBSTANCEADMIN createSUBSTANCEADMIN() {
        return new SUBSTANCEADMIN();
    }

    /**
     * Create an instance of {@link ORGANIZATION }
     * 
     */
    public ORGANIZATION createORGANIZATION() {
        return new ORGANIZATION();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORGANIZATION_NAME", scope = REPRESENTEDORGANIZATION.class)
    public JAXBElement<String> createREPRESENTEDORGANIZATIONORGANIZATIONNAME(String value) {
        return new JAXBElement<String>(_REPRESENTEDORGANIZATIONORGANIZATIONNAME_QNAME, String.class, REPRESENTEDORGANIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MEASURE_DATE_VALUE", scope = CLINICAL.class)
    public JAXBElement<String> createCLINICALMEASUREDATEVALUE(String value) {
        return new JAXBElement<String>(_CLINICALMEASUREDATEVALUE_QNAME, String.class, CLINICAL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONROUTECODE(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODE_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MATERIAL_CODE_DISPLAY_NAME", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONMATERIALCODEDISPLAYNAME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONMATERIALCODEDISPLAYNAME_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_QUANTITY", scope = IMMUNIZATION.class)
    public JAXBElement<Integer> createIMMUNIZATIONDOSEQUANTITY(Integer value) {
        return new JAXBElement<Integer>(_IMMUNIZATIONDOSEQUANTITY_QNAME, Integer.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE_DISPLAY_NAME", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONROUTECODEDISPLAYNAME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODEDISPLAYNAME_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MATERIAL_CODE_SYSTEM", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONMATERIALCODESYSTEM(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONMATERIALCODESYSTEM_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_PERIOD_VALUE", scope = IMMUNIZATION.class)
    public JAXBElement<Integer> createIMMUNIZATIONDOSEPERIODVALUE(Integer value) {
        return new JAXBElement<Integer>(_IMMUNIZATIONDOSEPERIODVALUE_QNAME, Integer.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE_SYSTEM_NAME", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONROUTECODESYSTEMNAME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODESYSTEMNAME_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_PERIOD_UNIT", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONDOSEPERIODUNIT(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONDOSEPERIODUNIT_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MATERIAL_CODE", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONMATERIALCODE(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONMATERIALCODE_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE_SYSTEM", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONROUTECODESYSTEM(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODESYSTEM_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_UNIT", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONDOSEUNIT(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONDOSEUNIT_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STATUS_CODE", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONSTATUSCODE(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONSTATUSCODE_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EFFECTIVE_DATE_TIME", scope = IMMUNIZATION.class)
    public JAXBElement<String> createIMMUNIZATIONEFFECTIVEDATETIME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONEFFECTIVEDATETIME_QNAME, String.class, IMMUNIZATION.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORDERED_TEST_ID", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTORDEREDTESTID(String value) {
        return new JAXBElement<String>(_TESTRESULTORDEREDTESTID_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORGANISM_IDENTIFIED", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTORGANISMIDENTIFIED(String value) {
        return new JAXBElement<String>(_TESTRESULTORGANISMIDENTIFIED_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OBSERVATION_CODE_TYPE", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTOBSERVATIONCODETYPE(String value) {
        return new JAXBElement<String>(_TESTRESULTOBSERVATIONCODETYPE_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_INTERPRETATION", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTTESTINTERPRETATION(String value) {
        return new JAXBElement<String>(_TESTRESULTTESTINTERPRETATION_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PERFORMING_LAB", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTPERFORMINGLAB(String value) {
        return new JAXBElement<String>(_TESTRESULTPERFORMINGLAB_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OBSERVATION_CODE", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTOBSERVATIONCODE(String value) {
        return new JAXBElement<String>(_TESTRESULTOBSERVATIONCODE_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SPECIMEN_ID", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTSPECIMENID(String value) {
        return new JAXBElement<String>(_TESTRESULTSPECIMENID_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RESULT", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTRESULT(String value) {
        return new JAXBElement<String>(_TESTRESULTRESULT_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RESULT_UNIT", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTRESULTUNIT(String value) {
        return new JAXBElement<String>(_TESTRESULTRESULTUNIT_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SPECIMEN_SOURCE", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTSPECIMENSOURCE(String value) {
        return new JAXBElement<String>(_TESTRESULTSPECIMENSOURCE_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_STATUS", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTTESTSTATUS(String value) {
        return new JAXBElement<String>(_TESTRESULTTESTSTATUS_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REPORTING_LAB_IDENTIFIER", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTREPORTINGLABIDENTIFIER(String value) {
        return new JAXBElement<String>(_TESTRESULTREPORTINGLABIDENTIFIER_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COLLECTION_DATE_TIME", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTCOLLECTIONDATETIME(String value) {
        return new JAXBElement<String>(_TESTRESULTCOLLECTIONDATETIME_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SUSCEPTIBILITY_TEST_INTERPRETATION", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTSUSCEPTIBILITYTESTINTERPRETATION(String value) {
        return new JAXBElement<String>(_TESTRESULTSUSCEPTIBILITYTESTINTERPRETATION_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REPORT_DATE_TIME", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTREPORTDATETIME(String value) {
        return new JAXBElement<String>(_TESTRESULTREPORTDATETIME_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORDERED_TEST_NAME", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTORDEREDTESTNAME(String value) {
        return new JAXBElement<String>(_TESTRESULTORDEREDTESTNAME_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RESULT_STATUS", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTRESULTSTATUS(String value) {
        return new JAXBElement<String>(_TESTRESULTRESULTSTATUS_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_INTERPRETATION_SYSTEM", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTTESTINTERPRETATIONSYSTEM(String value) {
        return new JAXBElement<String>(_TESTRESULTTESTINTERPRETATIONSYSTEM_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "METHOD_TYPE", scope = TESTRESULT.class)
    public JAXBElement<String> createTESTRESULTMETHODTYPE(String value) {
        return new JAXBElement<String>(_TESTRESULTMETHODTYPE_QNAME, String.class, TESTRESULT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORDER_DATE_TIME", scope = TESTORDER.class)
    public JAXBElement<String> createTESTORDERORDERDATETIME(String value) {
        return new JAXBElement<String>(_TESTORDERORDERDATETIME_QNAME, String.class, TESTORDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_PROCEDURE_CODE", scope = TESTORDER.class)
    public JAXBElement<String> createTESTORDERTESTPROCEDURECODE(String value) {
        return new JAXBElement<String>(_TESTORDERTESTPROCEDURECODE_QNAME, String.class, TESTORDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_PROCEDURE_NAME", scope = TESTORDER.class)
    public JAXBElement<String> createTESTORDERTESTPROCEDURENAME(String value) {
        return new JAXBElement<String>(_TESTORDERTESTPROCEDURENAME_QNAME, String.class, TESTORDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEST_PROCEDURE_CODE_TYPE", scope = TESTORDER.class)
    public JAXBElement<String> createTESTORDERTESTPROCEDURECODETYPE(String value) {
        return new JAXBElement<String>(_TESTORDERTESTPROCEDURECODETYPE_QNAME, String.class, TESTORDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DEATHS_IN_LAST_24_HOURS", scope = FACILITY.class, defaultValue = "0")
    public JAXBElement<Integer> createFACILITYDEATHSINLAST24HOURS(Integer value) {
        return new JAXBElement<Integer>(_FACILITYDEATHSINLAST24HOURS_QNAME, Integer.class, FACILITY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUMBER_OF_BEDS", scope = FACILITY.class, defaultValue = "0")
    public JAXBElement<Integer> createFACILITYNUMBEROFBEDS(Integer value) {
        return new JAXBElement<Integer>(_FACILITYNUMBEROFBEDS_QNAME, Integer.class, FACILITY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LAST_UPDATE_DATETIME", scope = FACILITY.class)
    public JAXBElement<String> createFACILITYLASTUPDATEDATETIME(String value) {
        return new JAXBElement<String>(_FACILITYLASTUPDATEDATETIME_QNAME, String.class, FACILITY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NUMBER_OF_ROOMS", scope = FACILITY.class, defaultValue = "0")
    public JAXBElement<Integer> createFACILITYNUMBEROFROOMS(Integer value) {
        return new JAXBElement<Integer>(_FACILITYNUMBEROFROOMS_QNAME, Integer.class, FACILITY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DISCHARGES_LAST_24_HOURS", scope = FACILITY.class, defaultValue = "0")
    public JAXBElement<Integer> createFACILITYDISCHARGESLAST24HOURS(Integer value) {
        return new JAXBElement<Integer>(_FACILITYDISCHARGESLAST24HOURS_QNAME, Integer.class, FACILITY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SENDING_FACILITY_ID", scope = FACILITY.class)
    public JAXBElement<String> createFACILITYSENDINGFACILITYID(String value) {
        return new JAXBElement<String>(_FACILITYSENDINGFACILITYID_QNAME, String.class, FACILITY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADMISSIONS_LAST_24_HOURS", scope = FACILITY.class, defaultValue = "0")
    public JAXBElement<Integer> createFACILITYADMISSIONSLAST24HOURS(Integer value) {
        return new JAXBElement<Integer>(_FACILITYADMISSIONSLAST24HOURS_QNAME, Integer.class, FACILITY.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROCEDURE_CODE_DISPLAY_NAME", scope = PROCEDURES.class)
    public JAXBElement<String> createPROCEDURESPROCEDURECODEDISPLAYNAME(String value) {
        return new JAXBElement<String>(_PROCEDURESPROCEDURECODEDISPLAYNAME_QNAME, String.class, PROCEDURES.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROCEDURE_CODE_SYSTEM", scope = PROCEDURES.class)
    public JAXBElement<String> createPROCEDURESPROCEDURECODESYSTEM(String value) {
        return new JAXBElement<String>(_PROCEDURESPROCEDURECODESYSTEM_QNAME, String.class, PROCEDURES.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STATUS_CODE", scope = PROCEDURES.class)
    public JAXBElement<String> createPROCEDURESSTATUSCODE(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONSTATUSCODE_QNAME, String.class, PROCEDURES.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROVIDER_EUID", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERPROVIDEREUID(String value) {
        return new JAXBElement<String>(_PROVIDERPROVIDEREUID_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FUNCTION_CODE_NAME", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERFUNCTIONCODENAME(String value) {
        return new JAXBElement<String>(_PROVIDERFUNCTIONCODENAME_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FUNCTION_CODE", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERFUNCTIONCODE(String value) {
        return new JAXBElement<String>(_PROVIDERFUNCTIONCODE_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PERSON_PREFIX", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERPERSONPREFIX(String value) {
        return new JAXBElement<String>(_PROVIDERPERSONPREFIX_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PERSON_FIRST_NAME", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERPERSONFIRSTNAME(String value) {
        return new JAXBElement<String>(_PROVIDERPERSONFIRSTNAME_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PERSON_LAST_NAME", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERPERSONLASTNAME(String value) {
        return new JAXBElement<String>(_PROVIDERPERSONLASTNAME_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORGANIZATION_OID", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERORGANIZATIONOID(String value) {
        return new JAXBElement<String>(_PROVIDERORGANIZATIONOID_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EVENT_END_DATE_TIME", scope = PROVIDER.class)
    public JAXBElement<XMLGregorianCalendar> createPROVIDEREVENTENDDATETIME(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PROVIDEREVENTENDDATETIME_QNAME, XMLGregorianCalendar.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FUNCTION_CODE_SYSTEM", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERFUNCTIONCODESYSTEM(String value) {
        return new JAXBElement<String>(_PROVIDERFUNCTIONCODESYSTEM_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORGANIZATION_NAME", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERORGANIZATIONNAME(String value) {
        return new JAXBElement<String>(_REPRESENTEDORGANIZATIONORGANIZATIONNAME_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOFTWARE_NAME", scope = PROVIDER.class)
    public JAXBElement<String> createPROVIDERSOFTWARENAME(String value) {
        return new JAXBElement<String>(_PROVIDERSOFTWARENAME_QNAME, String.class, PROVIDER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SNOWMED_DIAGNOSIS_CODE", scope = DIAGNOSIS.class)
    public JAXBElement<String> createDIAGNOSISSNOWMEDDIAGNOSISCODE(String value) {
        return new JAXBElement<String>(_DIAGNOSISSNOWMEDDIAGNOSISCODE_QNAME, String.class, DIAGNOSIS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RANK", scope = DIAGNOSIS.class)
    public JAXBElement<String> createDIAGNOSISRANK(String value) {
        return new JAXBElement<String>(_DIAGNOSISRANK_QNAME, String.class, DIAGNOSIS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DIAGNOSIS_STATUS", scope = DIAGNOSIS.class)
    public JAXBElement<String> createDIAGNOSISDIAGNOSISSTATUS(String value) {
        return new JAXBElement<String>(_DIAGNOSISDIAGNOSISSTATUS_QNAME, String.class, DIAGNOSIS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ICD9_DIAGNOSIS_CODE", scope = DIAGNOSIS.class)
    public JAXBElement<String> createDIAGNOSISICD9DIAGNOSISCODE(String value) {
        return new JAXBElement<String>(_DIAGNOSISICD9DIAGNOSISCODE_QNAME, String.class, DIAGNOSIS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DIAGNOSIS_CODE_DESC", scope = DIAGNOSIS.class)
    public JAXBElement<String> createDIAGNOSISDIAGNOSISCODEDESC(String value) {
        return new JAXBElement<String>(_DIAGNOSISDIAGNOSISCODEDESC_QNAME, String.class, DIAGNOSIS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PATIENT_ID", scope = ENCOUNTER.class)
    public JAXBElement<Integer> createENCOUNTERPATIENTID(Integer value) {
        return new JAXBElement<Integer>(_ENCOUNTERPATIENTID_QNAME, Integer.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DISCHARGE_DIAG_CODE", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERDISCHARGEDIAGCODE(String value) {
        return new JAXBElement<String>(_ENCOUNTERDISCHARGEDIAGCODE_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SYMPTOM_ILLNESS_ONSET_DATETIME", scope = ENCOUNTER.class)
    public JAXBElement<XMLGregorianCalendar> createENCOUNTERSYMPTOMILLNESSONSETDATETIME(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ENCOUNTERSYMPTOMILLNESSONSETDATETIME_QNAME, XMLGregorianCalendar.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LAST_UPDATE_DATE_TIME", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERLASTUPDATEDATETIME(String value) {
        return new JAXBElement<String>(_ENCOUNTERLASTUPDATEDATETIME_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADM_ENC_DATE_TIME", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERADMENCDATETIME(String value) {
        return new JAXBElement<String>(_ENCOUNTERADMENCDATETIME_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CHIEF_COMPLAINT", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERCHIEFCOMPLAINT(String value) {
        return new JAXBElement<String>(_ENCOUNTERCHIEFCOMPLAINT_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADM_TYPE", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERADMTYPE(String value) {
        return new JAXBElement<String>(_ENCOUNTERADMTYPE_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADM_CODE", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERADMCODE(String value) {
        return new JAXBElement<String>(_ENCOUNTERADMCODE_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DISCHARGE_DISPOSITION", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERDISCHARGEDISPOSITION(String value) {
        return new JAXBElement<String>(_ENCOUNTERDISCHARGEDISPOSITION_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DISCHARGE_DATE_TIME", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERDISCHARGEDATETIME(String value) {
        return new JAXBElement<String>(_ENCOUNTERDISCHARGEDATETIME_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PATIENT_CLASS", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERPATIENTCLASS(String value) {
        return new JAXBElement<String>(_ENCOUNTERPATIENTCLASS_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADMISSION_DIAG_CODE", scope = ENCOUNTER.class)
    public JAXBElement<String> createENCOUNTERADMISSIONDIAGCODE(String value) {
        return new JAXBElement<String>(_ENCOUNTERADMISSIONDIAGCODE_QNAME, String.class, ENCOUNTER.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ETHNICITY_CODE_SYSTEM", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTETHNICITYCODESYSTEM(String value) {
        return new JAXBElement<String>(_PATIENTETHNICITYCODESYSTEM_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GENDER_CODE_SYSTEM", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTGENDERCODESYSTEM(String value) {
        return new JAXBElement<String>(_PATIENTGENDERCODESYSTEM_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AGE_UNITS", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTAGEUNITS(String value) {
        return new JAXBElement<String>(_PATIENTAGEUNITS_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ZIP_CODE", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTZIPCODE(String value) {
        return new JAXBElement<String>(_PATIENTZIPCODE_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STATE", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTSTATE(String value) {
        return new JAXBElement<String>(_PATIENTSTATE_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AGE", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTAGE(String value) {
        return new JAXBElement<String>(_PATIENTAGE_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COUNTRY", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTCOUNTRY(String value) {
        return new JAXBElement<String>(_PATIENTCOUNTRY_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ETHNICITY_CODE", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTETHNICITYCODE(String value) {
        return new JAXBElement<String>(_PATIENTETHNICITYCODE_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCP_OID", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTPCPOID(String value) {
        return new JAXBElement<String>(_PATIENTPCPOID_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PATIENT_EUID", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTPATIENTEUID(String value) {
        return new JAXBElement<String>(_PATIENTPATIENTEUID_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TELEPHONE", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTTELEPHONE(String value) {
        return new JAXBElement<String>(_PATIENTTELEPHONE_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LAST_NAME", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTLASTNAME(String value) {
        return new JAXBElement<String>(_PATIENTLASTNAME_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COUNTY", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTCOUNTY(String value) {
        return new JAXBElement<String>(_PATIENTCOUNTY_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCP_NAME", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTPCPNAME(String value) {
        return new JAXBElement<String>(_PATIENTPCPNAME_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TRANSACTION_DATE_TIME", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTTRANSACTIONDATETIME(String value) {
        return new JAXBElement<String>(_PATIENTTRANSACTIONDATETIME_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIDDLE_INITIAL", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTMIDDLEINITIAL(String value) {
        return new JAXBElement<String>(_PATIENTMIDDLEINITIAL_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRST_NAME", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTFIRSTNAME(String value) {
        return new JAXBElement<String>(_PATIENTFIRSTNAME_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STREET_ADDRESS_2", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTSTREETADDRESS2(String value) {
        return new JAXBElement<String>(_PATIENTSTREETADDRESS2_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ETHNICITY_CODE_NAME", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTETHNICITYCODENAME(String value) {
        return new JAXBElement<String>(_PATIENTETHNICITYCODENAME_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STREET_ADDRESS_1", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTSTREETADDRESS1(String value) {
        return new JAXBElement<String>(_PATIENTSTREETADDRESS1_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GENDER_CODE", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTGENDERCODE(String value) {
        return new JAXBElement<String>(_PATIENTGENDERCODE_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CITY", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTCITY(String value) {
        return new JAXBElement<String>(_PATIENTCITY_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BIRTH_DATE_TIME", scope = PATIENT.class)
    public JAXBElement<String> createPATIENTBIRTHDATETIME(String value) {
        return new JAXBElement<String>(_PATIENTBIRTHDATETIME_QNAME, String.class, PATIENT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINROUTECODE(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODE_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MATERIAL_CODE_DISPLAY_NAME", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINMATERIALCODEDISPLAYNAME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONMATERIALCODEDISPLAYNAME_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_QUANTITY", scope = SUBSTANCEADMIN.class)
    public JAXBElement<Integer> createSUBSTANCEADMINDOSEQUANTITY(Integer value) {
        return new JAXBElement<Integer>(_IMMUNIZATIONDOSEQUANTITY_QNAME, Integer.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE_DISPLAY_NAME", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINROUTECODEDISPLAYNAME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODEDISPLAYNAME_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MATERIAL_CODE_SYSTEM", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINMATERIALCODESYSTEM(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONMATERIALCODESYSTEM_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_PERIOD_VALUE", scope = SUBSTANCEADMIN.class)
    public JAXBElement<Integer> createSUBSTANCEADMINDOSEPERIODVALUE(Integer value) {
        return new JAXBElement<Integer>(_IMMUNIZATIONDOSEPERIODVALUE_QNAME, Integer.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE_SYSTEM_NAME", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINROUTECODESYSTEMNAME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODESYSTEMNAME_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_PERIOD_UNIT", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINDOSEPERIODUNIT(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONDOSEPERIODUNIT_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MATERIAL_CODE", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINMATERIALCODE(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONMATERIALCODE_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUTE_CODE_SYSTEM", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINROUTECODESYSTEM(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONROUTECODESYSTEM_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOSE_UNIT", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINDOSEUNIT(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONDOSEUNIT_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STATUS_CODE", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINSTATUSCODE(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONSTATUSCODE_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EFFECTIVE_DATE_TIME", scope = SUBSTANCEADMIN.class)
    public JAXBElement<String> createSUBSTANCEADMINEFFECTIVEDATETIME(String value) {
        return new JAXBElement<String>(_IMMUNIZATIONEFFECTIVEDATETIME_QNAME, String.class, SUBSTANCEADMIN.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORGANIZATION_NAME", scope = ORGANIZATION.class)
    public JAXBElement<String> createORGANIZATIONORGANIZATIONNAME(String value) {
        return new JAXBElement<String>(_REPRESENTEDORGANIZATIONORGANIZATIONNAME_QNAME, String.class, ORGANIZATION.class, value);
    }

}
